### ISSUE TITLE
Package doctrine/cache deprecated

### ISSUE THREAD

**Issue by marioradu05** [dotkernel/api#105]
The `doctrine/cache` package is deprecated in version `1.11` (currently used) without any suggested replacement, it will be removed from version `2.0`.
The package is required by: 

- doctrine/dbal 
- doctrine/orm
- doctrine/persistence
- dotkernel/dot-annotated-services
- roave/psr-container-doctrine 

This issue also may apply to frontend and admin repositories.
We should keep this package version locked, until the above package maintainers decide on how to handle this.

**Comment by bidi47** [comment]
checked both api and frontend
at the moment there is no need to replace the package doctrine/cache (symfony/cache and laminas/laminas-cache are alternatives)
doctrine/cache 1.12.1 is installed at this point due to requirements from other packages

will reopen the issue when current packages are set to be updated to newer major versions (e.g. that support php ^8)
