### ISSUE TITLE
authentication config in local.php

### ISSUE THREAD

**Issue by bidi47** [dotkernel/api#112]
after a recent update to an api i got an error detailed below
if didn't find if this was covered in previous issues
we should also consider updating file _config/autoload/local.php.dist_ in the api basecode

the error
`TypeError raised in file
\api\vendor\mezzio\mezzio-authentication-oauth2\src\ConfigTrait.php line 24:
Message: Return value of Mezzio\Authentication\OAuth2\AuthorizationServerFactory::getPrivateKey() must be of the type
string, array returned`

it's caused by the _getPrivateKey()_ function in _mezzio/mezzio-authentication-oauth2_ version 2.4.0 that now explicitly requires the return of a string

the fix is to update our _config/autoload/local.php_ from
`'private_key'    => [
            'key_or_path' => getcwd() . '/data/oauth/private.key',
            'key_permissions_check' => false
        ],`
to
`'private_key'    => file_get_contents(getcwd() . '/data/oauth/private.key'),`

**Comment by kakapiciu** [comment]
no need to modify config
they just release 2.4.1 with reverting BC break and allowing array structures for private keys, rather than just string

https://github.com/mezzio/mezzio-authentication-oauth2/pull/48

Recomandation: specific require in composer.json mezzio/mezzio-authentication-oauth2 ^2.4.1
