### ISSUE TITLE
Doctrine - Migration does not use transaction

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api#115]

**Comment by alexmerlin** [comment]
This could be an issue only for Doctrine version lower than 3, because for Doctrine 3.*, according to their [documentation](https://www.doctrine-project.org/projects/doctrine-migrations/en/3.3/reference/configuration.html#using-or-not-using-transactions):

> By default, migrations are transactional, meaning code in a migration is wrapped in a transaction. Setting transactional to false will disable that.

Also, when running multiple migrations, we have [all_or_nothing](https://www.doctrine-project.org/projects/doctrine-migrations/en/3.3/reference/configuration.html#all-or-nothing-transaction) enabled in [migrations.php](https://github.com/dotkernel/api/blob/3.0/migrations.php#L14):
> When using the all_or_nothing option, multiple migrations ran at the same time will be wrapped in a single transaction. If one migration fails, all migrations will be rolled back

**Comment by arhimede** [comment]
@cPintiuta i am adding Claudiu to the thread as he is the one which encountered the issue 
Please add the Doctrine version and stuff
