### ISSUE TITLE
check the sendMail function to log error 

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api#118]
connected to issue 
https://github.com/dotkernel/frontend/issues/289

**Comment by arhimede** [comment]
@bidi47  please check this one

**Comment by bidi47** [comment]
i've found an instance where the mail send error isn't visible
because both dot-mail and the frontend code that tries to send an email have try-catch statements

so even if dot-mail returns an message with the reason the email transfer failed, it's not an exception, so the frontend try-catch considers it a successful email transfer

what is the best way to proceed? 
to remove the try-catches from 
- frontend
- or dot-mail (faster and allows the frontend to display custom error messages)

**Comment by bidi47** [comment]
resolved in the most recent versions of dot-mail
dot-mail 3.4.6 and 4.0.4
