### ISSUE TITLE
article related to error endpoint

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api#188]
Please extend the documnetation about error endpoint

**Comment by arhimede** [comment]
@bidi47 document this error collector endpoint 
on both dotkernel.com and in docs.dotkernel.org

**Comment by arhimede** [comment]
`| POST   | error.report                    | /error-report    `

**Comment by bidi47** [comment]
we should discuss the feature before updating the docs

the article is here
https://git.apidemia.net/websites/dotkernel.org/-/wikis/Error-reporting-API
most of it will go in the docs too

my issue when testing with Postman was 
- function `isMatchingDomain()` in `App/src/Service/ErrorReportingService.php` checks `$request->getServerParams()['HTTP_ORIGIN']` which was null on my end. it worked with HTTP_HOST, though i'm unsure that is the intent here
- the 'domain_whitelist' key in `config/autoload/erro-handling.global.php` fails validation when empty. i added `localhost` to pass this test. note that an empty `ip_whitelist` passes the test

**Comment by alexmerlin** [comment]
The header `HTTP_ORIGIN` is not sent via Postman unless manually added as a header with the key `Origin` and the value `http://api.dotkernel.localhost` (or the local domain your API is hosted on).
On production applications this header **should** always be set (not only for the error-reporting feature, but CORS as well).

**Note**: Origin is the URL of application which consumes the API.

Indeed, either the `domain_whitelist` or `ip_whitelist` should have value(s), because when [checkRequest](https://github.com/dotkernel/api/blob/5.0/src/App/src/Service/ErrorReportService.php#L65) tries to validate the request, if both `isMatchingDomain` and `isMatchingIpAddress` return false, a `ForbiddenException` is thrown and the error message does not get stored.

Regarding the article, you should add to [this](https://git.apidemia.net/websites/dotkernel.org/-/wikis/Error-reporting-API#generating-a-token-and-adding-it-to-your-api-config) section the above details, where you explain that either the origin's domain or IP address must be whitelisted.

---

To summarize, for an application to be able to send error messages to Dotkernel API:

- server-side requirements in `config/autoload/error-handling.global.php` (may also be set/overwritten in `config/autoload/local.php`):
  - all keys (`enabled`, `path`, `tokens`, `domain_whitelist` and `ip_whitelist`) must exist under `ErrorReportServiceInterface::class`
  - feature must be enabled via `ErrorReportServiceInterface::class` . `enabled` => `true`
  - `ErrorReportServiceInterface::class` . `path` must have a value - if the file from the path does not exist, it will be created
  - `ErrorReportServiceInterface::class` . `tokens` must contain at least one token
  - either of `ErrorReportServiceInterface::class` . `domain_whitelist`/`ip_whitelist` must have at least one value
- application-side requirements:
  - send `Error-Reporting-Token` header with a valid token previously stored in `config/autoload/error-handling.global.php` in the `ErrorReportServiceInterface::class` . `tokens` array
  - send `Origin` header set to the application's URL

**Note**:

- tokens found under `ErrorReportServiceInterface::class` . `tokens` do not expire
- the log file stores the token too, so that you can identify which application sent the error message

### Tips and tricks:
If there are multiple applications that report errors to your API, each with its own error reporting token, you can store the tokens as key-value pairs where the key is an alias that describes the application whom the token was assigned to and the value is the token used by that application.
Example:
```php
// ...
return [
    ...
    ErrorReportServiceInterface::class => [
        // ...
        'tokens' => [
            'frontend' => '0123456789abcdef0123456789abcdef01234567',
            'admin' => '9876543210abcdef0123456789abcdef7654321',
            // other tokens
        ],
    ],
];
```

Then, in the log file you will see entries similar to the below:

> [1997-08-29 02:14:00] [0123456789abcdef0123456789abcdef01234567] Demo error message

From this you can identify that the error message cam from the application that uses the `0123456789abcdef0123456789abcdef01234567` token, which - based on the mapping - is `frontend` in this case.

**Comment by bidi47** [comment]
the article is posted here 
https://www.dotkernel.com/dotkernel-api/error-reporting-endpoint-in-dotkernel-api/
and included in the docs
https://docs.dotkernel.org/api-documentation/v5/core-features/error-reporting/
